import { FeatureRequest } from "./types";

export const initialFeatures: FeatureRequest[] = [
  {
    id: "1",
    title: "Dark Mode Support",
    description: "It would be great to have a dark mode for late night work.",
    status: "in-progress",
    votes: 42,
    author: "Alice Johnson",
    createdAt: "2023-10-01",
    tags: ["UI", "Accessibility"],
    comments: [
      {
        id: "c1",
        author: "Bob Smith",
        avatar: "/avatars/02.png",
        content: "I agree, this is essential.",
        createdAt: "2023-10-02",
      },
    ],
  },
  {
    id: "2",
    title: "Mobile App",
    description: "A dedicated mobile app for iOS and Android.",
    status: "planned",
    votes: 120,
    author: "Charlie Brown",
    createdAt: "2023-09-15",
    tags: ["Mobile", "Platform"],
    comments: [],
  },
  {
    id: "3",
    title: "API Access",
    description: "Allow us to access our data via API.",
    status: "under-review",
    votes: 15,
    author: "Dave Wilson",
    createdAt: "2023-10-05",
    tags: ["Dev", "Integration"],
    comments: [],
  },
  {
    id: "4",
    title: "Export to PDF",
    description: "Export reports to PDF format.",
    status: "done",
    votes: 89,
    author: "Eve Davis",
    createdAt: "2023-08-20",
    tags: ["Reporting"],
    comments: [],
  },
  {
    id: "5",
    title: "Calendar Integration",
    description: "Sync events with Google Calendar.",
    status: "planned",
    votes: 55,
    author: "Frank Miller",
    createdAt: "2023-10-10",
    tags: ["Integration", "Productivity"],
    comments: [],
  },
  {
    id: "6",
    title: "Recurring Billing Automation",
    description: "Automate monthly membership billing and failed payment retries.",
    status: "under-review",
    votes: 78,
    author: "Sarah Connor",
    createdAt: "2023-10-15",
    tags: ["Finance", "Automation"],
    comments: [],
  },
  {
    id: "7",
    title: "Video Analysis Tools",
    description: "Allow coaches to upload training videos and add annotations/voiceovers for athlete feedback.",
    status: "planned",
    votes: 156,
    author: "Coach Carter",
    createdAt: "2023-09-28",
    tags: ["Training", "Video"],
    comments: [
      {
        id: "c2",
        author: "Mike Ross",
        avatar: "/avatars/03.png",
        content: "This would be a game changer for remote coaching.",
        createdAt: "2023-10-05",
      }
    ],
  },
  {
    id: "8",
    title: "Parent/Guardian Portal",
    description: "A separate login for parents to manage multiple athletes, pay bills, and view schedules.",
    status: "in-progress",
    votes: 92,
    author: "Martha Kent",
    createdAt: "2023-10-08",
    tags: ["User Management", "Access"],
    comments: [],
  },
  {
    id: "9",
    title: "Wearable Device Sync",
    description: "Integration with Apple Health and Garmin to pull in athlete workout data automatically.",
    status: "under-review",
    votes: 45,
    author: "Tony Stark",
    createdAt: "2023-10-18",
    tags: ["Integration", "Health"],
    comments: [],
  },
  {
    id: "10",
    title: "Digital Waivers & Forms",
    description: "Paperless waiver signing and document management for new athlete onboarding.",
    status: "planned",
    votes: 67,
    author: "Matt Murdock",
    createdAt: "2023-10-12",
    tags: ["Legal", "Onboarding"],
    comments: [],
  },
];
