import { NextRequest, NextResponse } from "next/server";
import { getAuthSession } from "@/lib/auth";
import { getScopedDb } from "@/lib/db";
import { checkFeatureGate } from "@/lib/feature-resolver";
import { parseDateOnly } from "@/lib/date-utils";
import { z } from "zod";

const updateInstanceSchema = z.object({
  name: z.string().min(1).optional(),
  price: z.number().min(0).optional(),
  billingInterval: z.enum(["ONE_TIME", "MONTHLY", "YEARLY", "SESSION"]).optional(),
  startDate: z
    .string()
    .optional()
    .transform((str) => (str ? (parseDateOnly(str) ?? undefined) : undefined)),
  endDate: z
    .string()
    .optional()
    .transform((str) => (str ? (parseDateOnly(str) ?? undefined) : undefined)),
  autoRenewDate: z
    .string()
    .nullable()
    .optional()
    .transform((val) =>
      val === null ? null : val ? (parseDateOnly(val) ?? undefined) : undefined
    ),
  purchaseStartDate: z
    .string()
    .nullable()
    .optional()
    .transform((val) =>
      val === null ? null : val ? (parseDateOnly(val) ?? undefined) : undefined
    ),
  purchaseEndDate: z
    .string()
    .nullable()
    .optional()
    .transform((val) =>
      val === null ? null : val ? (parseDateOnly(val) ?? undefined) : undefined
    ),
  capacity: z.number().int().min(0).nullable().optional(),
  status: z.enum(["DRAFT", "ACTIVE", "EXPIRED", "CANCELLED", "ARCHIVED"]).optional(),
  // Registration window
  registrationStartDate: z
    .string()
    .nullable()
    .optional()
    .transform((val) =>
      val === null ? null : val ? (parseDateOnly(val) ?? undefined) : undefined
    ),
  registrationStartTime: z.string().nullable().optional(),
  registrationEndDate: z
    .string()
    .nullable()
    .optional()
    .transform((val) =>
      val === null ? null : val ? (parseDateOnly(val) ?? undefined) : undefined
    ),
  registrationEndTime: z.string().nullable().optional(),
  registrationOpen: z.boolean().optional(),
  earlyAccessCode: z.string().nullable().optional(),
});

// GET /api/memberships/[id]/instances/[instanceId]
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string; instanceId: string } }
) {
  try {
    const session = await getAuthSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const gate = await checkFeatureGate(session.user.organizationId, "memberships");
    if (gate) return gate;

    const scopedDb = getScopedDb(session.user.organizationId);

    const instance = await scopedDb.membershipInstance.findFirst({
      where: {
        id: params.instanceId,
        membershipGroupId: params.id,
      },
      include: {
        group: true,
        _count: { select: { athleteMemberships: true } },
      },
    });

    if (!instance) {
      return NextResponse.json({ error: "Instance not found" }, { status: 404 });
    }

    return NextResponse.json(instance);
  } catch (error) {
    console.error("Error fetching instance:", error);
    return NextResponse.json({ error: "Failed to fetch instance" }, { status: 500 });
  }
}

// PATCH /api/memberships/[id]/instances/[instanceId] - Update or publish instance
export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string; instanceId: string } }
) {
  try {
    const session = await getAuthSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const gate = await checkFeatureGate(session.user.organizationId, "memberships");
    if (gate) return gate;

    const permissions = session.user.permissions || [];
    if (!permissions.includes("*") && !permissions.includes("training.edit")) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await request.json();
    const validatedData = updateInstanceSchema.parse(body);
    const scopedDb = getScopedDb(session.user.organizationId);

    const existing = await scopedDb.membershipInstance.findFirst({
      where: {
        id: params.instanceId,
        membershipGroupId: params.id,
      },
      include: { group: true },
    });

    if (!existing) {
      return NextResponse.json({ error: "Instance not found" }, { status: 404 });
    }

    // For non-recurring auto-generated instances, prevent changing certain fields
    if (existing.isAutoGenerated && !existing.group.isRecurring) {
      if (validatedData.startDate || validatedData.endDate || validatedData.billingInterval) {
        return NextResponse.json(
          {
            error:
              "Cannot modify dates or billing interval of auto-generated non-recurring instances. Update the group instead.",
          },
          { status: 400 }
        );
      }
    }

    // Build update data, filtering out undefined values
    const updateData: Record<string, unknown> = {};
    if (validatedData.name !== undefined) updateData.name = validatedData.name;
    if (validatedData.price !== undefined) updateData.price = validatedData.price;
    if (validatedData.billingInterval !== undefined)
      updateData.billingInterval = validatedData.billingInterval;
    if (validatedData.startDate !== undefined) updateData.startDate = validatedData.startDate;
    if (validatedData.endDate !== undefined) updateData.endDate = validatedData.endDate;
    if (validatedData.autoRenewDate !== undefined)
      updateData.autoRenewDate = validatedData.autoRenewDate;
    if (validatedData.purchaseStartDate !== undefined)
      updateData.purchaseStartDate = validatedData.purchaseStartDate;
    if (validatedData.purchaseEndDate !== undefined)
      updateData.purchaseEndDate = validatedData.purchaseEndDate;
    if (validatedData.capacity !== undefined) updateData.capacity = validatedData.capacity;
    if (validatedData.status !== undefined) updateData.status = validatedData.status;
    if (validatedData.registrationStartDate !== undefined)
      updateData.registrationStartDate = validatedData.registrationStartDate;
    if (validatedData.registrationStartTime !== undefined)
      updateData.registrationStartTime = validatedData.registrationStartTime;
    if (validatedData.registrationEndDate !== undefined)
      updateData.registrationEndDate = validatedData.registrationEndDate;
    if (validatedData.registrationEndTime !== undefined)
      updateData.registrationEndTime = validatedData.registrationEndTime;
    if (validatedData.registrationOpen !== undefined)
      updateData.registrationOpen = validatedData.registrationOpen;
    if (validatedData.earlyAccessCode !== undefined)
      updateData.earlyAccessCode = validatedData.earlyAccessCode;

    const instance = await scopedDb.membershipInstance.update({
      where: { id: params.instanceId },
      data: updateData,
      include: {
        group: true,
        _count: { select: { athleteMemberships: true } },
      },
    });

    return NextResponse.json(instance);
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.issues[0].message }, { status: 400 });
    }
    console.error("Error updating instance:", error);
    return NextResponse.json({ error: "Failed to update instance" }, { status: 500 });
  }
}

// DELETE /api/memberships/[id]/instances/[instanceId]
export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string; instanceId: string } }
) {
  try {
    const session = await getAuthSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const gate = await checkFeatureGate(session.user.organizationId, "memberships");
    if (gate) return gate;

    const permissions = session.user.permissions || [];
    if (!permissions.includes("*") && !permissions.includes("training.delete")) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const scopedDb = getScopedDb(session.user.organizationId);

    const instance = await scopedDb.membershipInstance.findFirst({
      where: {
        id: params.instanceId,
        membershipGroupId: params.id,
      },
      include: { group: true },
    });

    if (!instance) {
      return NextResponse.json({ error: "Instance not found" }, { status: 404 });
    }

    // Prevent deleting auto-generated instances for non-recurring groups
    if (instance.isAutoGenerated && !instance.group.isRecurring) {
      return NextResponse.json(
        {
          error:
            "Cannot delete the auto-generated instance of a non-recurring membership group. Delete the group instead.",
        },
        { status: 400 }
      );
    }

    // Prevent deleting instances with existing athlete memberships
    const membershipCount = await scopedDb.athleteMembership.count({
      where: { membershipInstanceId: params.instanceId },
    });

    if (membershipCount > 0) {
      return NextResponse.json(
        {
          error: `Cannot delete instance with ${membershipCount} active membership(s). Archive it instead.`,
        },
        { status: 400 }
      );
    }

    await scopedDb.membershipInstance.delete({
      where: { id: params.instanceId },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error deleting instance:", error);
    return NextResponse.json({ error: "Failed to delete instance" }, { status: 500 });
  }
}
