/**
 * ISU figure-skating element catalog — static data module.
 *
 * Base values sourced from ISU Communication 2430 (2022) and confirmed against
 * Skate Canada's published Scale of Values for the 2025-26 season.
 * All GOE bounds reflect the −5 / +5 scale adopted for the 2018-19 season.
 *
 * This file is intentionally a pure data export with no database writes.
 * Phase 4.3 (planned-program builder) will import ISU_ELEMENTS and persist
 * rows to the planned IsuElement Prisma table.
 *
 * Lifts (pairs) and throw jumps include a representative sample only.
 * Additional lift groups, twist-lift grades, and throw rotations can be
 * appended in Phase 4.3 once the full pairs element set is scoped.
 */

/** Canonical ISU element descriptor, mirroring the planned IsuElement Prisma model. */
export interface IsuElement {
  /** Canonical short code compatible with Phase 4.2 shorthand generator, e.g. "3T", "FSSp4". */
  code: string;
  /** Human-readable name in title case, e.g. "Triple Toe Loop". */
  name: string;
  /** Broad element category. */
  kind: "jump" | "spin" | "stepSequence" | "chorSequence" | "throw" | "lift" | "deathSpiral";
  /** ISU base value for the 2025-26 season, rounded to 2 decimal places. */
  baseValue: number;
  /** Minimum GOE (−5 since the 2018-19 season). */
  goeMin: number;
  /** Maximum GOE (+5 since the 2018-19 season). */
  goeMax: number;
  /**
   * Number of full rotations (jumps and throws).
   * The Axel family is labelled by takeoff rotation count (1A = 1 even though
   * it is actually 1½ revolutions in the air).
   */
  turns?: number;
  /** Jump edge / toe-pick takeoff classification. */
  jumpType?: "T" | "S" | "Lo" | "F" | "Lz" | "A";
  /**
   * Spin family abbreviation matching the code prefix, e.g. "USp", "FSSp".
   * Flying variants are distinguished by the leading "F" in the family name.
   */
  spinFamily?: string;
  /** ISU level designation (spins, step sequences, death spirals). */
  level?: "B" | 1 | 2 | 3 | 4;
  /**
   * Death-spiral pivot-edge entry direction (pairs only).
   * FoI = forward-outside inside, FoO = forward-outside outside,
   * BoI = backward-outside inside, BoO = backward-outside outside.
   * Maps to ISU codes FiDs / FoDs / BiDs / BoDs respectively.
   */
  entry?: "FoI" | "FoO" | "BoI" | "BoO";
}

export const ISU_ELEMENTS: IsuElement[] = [
  // ── JUMPS ──────────────────────────────────────────────────────────────────
  // Singles
  {
    code: "1T",
    name: "Single Toe Loop",
    kind: "jump",
    jumpType: "T",
    turns: 1,
    baseValue: 0.4,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "1S",
    name: "Single Salchow",
    kind: "jump",
    jumpType: "S",
    turns: 1,
    baseValue: 0.4,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "1Lo",
    name: "Single Loop",
    kind: "jump",
    jumpType: "Lo",
    turns: 1,
    baseValue: 0.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "1F",
    name: "Single Flip",
    kind: "jump",
    jumpType: "F",
    turns: 1,
    baseValue: 0.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "1Lz",
    name: "Single Lutz",
    kind: "jump",
    jumpType: "Lz",
    turns: 1,
    baseValue: 0.6,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "1A",
    name: "Single Axel",
    kind: "jump",
    jumpType: "A",
    turns: 1,
    baseValue: 1.1,
    goeMin: -5,
    goeMax: 5,
  },
  // Doubles
  {
    code: "2T",
    name: "Double Toe Loop",
    kind: "jump",
    jumpType: "T",
    turns: 2,
    baseValue: 1.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "2S",
    name: "Double Salchow",
    kind: "jump",
    jumpType: "S",
    turns: 2,
    baseValue: 1.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "2Lo",
    name: "Double Loop",
    kind: "jump",
    jumpType: "Lo",
    turns: 2,
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "2F",
    name: "Double Flip",
    kind: "jump",
    jumpType: "F",
    turns: 2,
    baseValue: 1.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "2Lz",
    name: "Double Lutz",
    kind: "jump",
    jumpType: "Lz",
    turns: 2,
    baseValue: 2.1,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "2A",
    name: "Double Axel",
    kind: "jump",
    jumpType: "A",
    turns: 2,
    baseValue: 3.3,
    goeMin: -5,
    goeMax: 5,
  },
  // Triples
  {
    code: "3T",
    name: "Triple Toe Loop",
    kind: "jump",
    jumpType: "T",
    turns: 3,
    baseValue: 4.2,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3S",
    name: "Triple Salchow",
    kind: "jump",
    jumpType: "S",
    turns: 3,
    baseValue: 4.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3Lo",
    name: "Triple Loop",
    kind: "jump",
    jumpType: "Lo",
    turns: 3,
    baseValue: 4.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3F",
    name: "Triple Flip",
    kind: "jump",
    jumpType: "F",
    turns: 3,
    baseValue: 5.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3Lz",
    name: "Triple Lutz",
    kind: "jump",
    jumpType: "Lz",
    turns: 3,
    baseValue: 5.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3A",
    name: "Triple Axel",
    kind: "jump",
    jumpType: "A",
    turns: 3,
    baseValue: 8.0,
    goeMin: -5,
    goeMax: 5,
  },
  // Quadruples
  {
    code: "4T",
    name: "Quadruple Toe Loop",
    kind: "jump",
    jumpType: "T",
    turns: 4,
    baseValue: 9.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4S",
    name: "Quadruple Salchow",
    kind: "jump",
    jumpType: "S",
    turns: 4,
    baseValue: 9.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4Lo",
    name: "Quadruple Loop",
    kind: "jump",
    jumpType: "Lo",
    turns: 4,
    baseValue: 10.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4F",
    name: "Quadruple Flip",
    kind: "jump",
    jumpType: "F",
    turns: 4,
    baseValue: 11.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4Lz",
    name: "Quadruple Lutz",
    kind: "jump",
    jumpType: "Lz",
    turns: 4,
    baseValue: 11.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4A",
    name: "Quadruple Axel",
    kind: "jump",
    jumpType: "A",
    turns: 4,
    baseValue: 12.5,
    goeMin: -5,
    goeMax: 5,
  },

  // ── SPINS ──────────────────────────────────────────────────────────────────
  // Upright Spin (USp)
  {
    code: "USpB",
    name: "Upright Spin Basic",
    kind: "spin",
    spinFamily: "USp",
    level: "B",
    baseValue: 1.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "USp1",
    name: "Upright Spin Level 1",
    kind: "spin",
    spinFamily: "USp",
    level: 1,
    baseValue: 1.2,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "USp2",
    name: "Upright Spin Level 2",
    kind: "spin",
    spinFamily: "USp",
    level: 2,
    baseValue: 1.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "USp3",
    name: "Upright Spin Level 3",
    kind: "spin",
    spinFamily: "USp",
    level: 3,
    baseValue: 1.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "USp4",
    name: "Upright Spin Level 4",
    kind: "spin",
    spinFamily: "USp",
    level: 4,
    baseValue: 2.4,
    goeMin: -5,
    goeMax: 5,
  },
  // Sit Spin (SSp)
  {
    code: "SSpB",
    name: "Sit Spin Basic",
    kind: "spin",
    spinFamily: "SSp",
    level: "B",
    baseValue: 1.1,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "SSp1",
    name: "Sit Spin Level 1",
    kind: "spin",
    spinFamily: "SSp",
    level: 1,
    baseValue: 1.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "SSp2",
    name: "Sit Spin Level 2",
    kind: "spin",
    spinFamily: "SSp",
    level: 2,
    baseValue: 1.6,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "SSp3",
    name: "Sit Spin Level 3",
    kind: "spin",
    spinFamily: "SSp",
    level: 3,
    baseValue: 2.1,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "SSp4",
    name: "Sit Spin Level 4",
    kind: "spin",
    spinFamily: "SSp",
    level: 4,
    baseValue: 2.7,
    goeMin: -5,
    goeMax: 5,
  },
  // Layback Spin (LSp)
  {
    code: "LSpB",
    name: "Layback Spin Basic",
    kind: "spin",
    spinFamily: "LSp",
    level: "B",
    baseValue: 1.2,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "LSp1",
    name: "Layback Spin Level 1",
    kind: "spin",
    spinFamily: "LSp",
    level: 1,
    baseValue: 1.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "LSp2",
    name: "Layback Spin Level 2",
    kind: "spin",
    spinFamily: "LSp",
    level: 2,
    baseValue: 1.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "LSp3",
    name: "Layback Spin Level 3",
    kind: "spin",
    spinFamily: "LSp",
    level: 3,
    baseValue: 2.4,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "LSp4",
    name: "Layback Spin Level 4",
    kind: "spin",
    spinFamily: "LSp",
    level: 4,
    baseValue: 3.0,
    goeMin: -5,
    goeMax: 5,
  },
  // Camel Spin (CSp)
  {
    code: "CSpB",
    name: "Camel Spin Basic",
    kind: "spin",
    spinFamily: "CSp",
    level: "B",
    baseValue: 1.1,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CSp1",
    name: "Camel Spin Level 1",
    kind: "spin",
    spinFamily: "CSp",
    level: 1,
    baseValue: 1.4,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CSp2",
    name: "Camel Spin Level 2",
    kind: "spin",
    spinFamily: "CSp",
    level: 2,
    baseValue: 1.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CSp3",
    name: "Camel Spin Level 3",
    kind: "spin",
    spinFamily: "CSp",
    level: 3,
    baseValue: 2.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CSp4",
    name: "Camel Spin Level 4",
    kind: "spin",
    spinFamily: "CSp",
    level: 4,
    baseValue: 2.9,
    goeMin: -5,
    goeMax: 5,
  },
  // Combination Spin (CoSp)
  {
    code: "CoSpB",
    name: "Combination Spin Basic",
    kind: "spin",
    spinFamily: "CoSp",
    level: "B",
    baseValue: 1.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CoSp1",
    name: "Combination Spin Level 1",
    kind: "spin",
    spinFamily: "CoSp",
    level: 1,
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CoSp2",
    name: "Combination Spin Level 2",
    kind: "spin",
    spinFamily: "CoSp",
    level: 2,
    baseValue: 2.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CoSp3",
    name: "Combination Spin Level 3",
    kind: "spin",
    spinFamily: "CoSp",
    level: 3,
    baseValue: 3.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "CoSp4",
    name: "Combination Spin Level 4",
    kind: "spin",
    spinFamily: "CoSp",
    level: 4,
    baseValue: 3.5,
    goeMin: -5,
    goeMax: 5,
  },
  // Flying Upright Spin (FUSp)
  {
    code: "FUSpB",
    name: "Flying Upright Spin Basic",
    kind: "spin",
    spinFamily: "FUSp",
    level: "B",
    baseValue: 1.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FUSp1",
    name: "Flying Upright Spin Level 1",
    kind: "spin",
    spinFamily: "FUSp",
    level: 1,
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FUSp2",
    name: "Flying Upright Spin Level 2",
    kind: "spin",
    spinFamily: "FUSp",
    level: 2,
    baseValue: 2.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FUSp3",
    name: "Flying Upright Spin Level 3",
    kind: "spin",
    spinFamily: "FUSp",
    level: 3,
    baseValue: 2.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FUSp4",
    name: "Flying Upright Spin Level 4",
    kind: "spin",
    spinFamily: "FUSp",
    level: 4,
    baseValue: 3.2,
    goeMin: -5,
    goeMax: 5,
  },
  // Flying Sit Spin (FSSp)
  {
    code: "FSSpB",
    name: "Flying Sit Spin Basic",
    kind: "spin",
    spinFamily: "FSSp",
    level: "B",
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FSSp1",
    name: "Flying Sit Spin Level 1",
    kind: "spin",
    spinFamily: "FSSp",
    level: 1,
    baseValue: 1.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FSSp2",
    name: "Flying Sit Spin Level 2",
    kind: "spin",
    spinFamily: "FSSp",
    level: 2,
    baseValue: 2.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FSSp3",
    name: "Flying Sit Spin Level 3",
    kind: "spin",
    spinFamily: "FSSp",
    level: 3,
    baseValue: 2.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FSSp4",
    name: "Flying Sit Spin Level 4",
    kind: "spin",
    spinFamily: "FSSp",
    level: 4,
    baseValue: 3.5,
    goeMin: -5,
    goeMax: 5,
  },
  // Flying Layback Spin (FLSp)
  {
    code: "FLSpB",
    name: "Flying Layback Spin Basic",
    kind: "spin",
    spinFamily: "FLSp",
    level: "B",
    baseValue: 1.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FLSp1",
    name: "Flying Layback Spin Level 1",
    kind: "spin",
    spinFamily: "FLSp",
    level: 1,
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FLSp2",
    name: "Flying Layback Spin Level 2",
    kind: "spin",
    spinFamily: "FLSp",
    level: 2,
    baseValue: 2.1,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FLSp3",
    name: "Flying Layback Spin Level 3",
    kind: "spin",
    spinFamily: "FLSp",
    level: 3,
    baseValue: 2.6,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FLSp4",
    name: "Flying Layback Spin Level 4",
    kind: "spin",
    spinFamily: "FLSp",
    level: 4,
    baseValue: 3.2,
    goeMin: -5,
    goeMax: 5,
  },
  // Flying Camel Spin (FCSp)
  {
    code: "FCSpB",
    name: "Flying Camel Spin Basic",
    kind: "spin",
    spinFamily: "FCSp",
    level: "B",
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCSp1",
    name: "Flying Camel Spin Level 1",
    kind: "spin",
    spinFamily: "FCSp",
    level: 1,
    baseValue: 1.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCSp2",
    name: "Flying Camel Spin Level 2",
    kind: "spin",
    spinFamily: "FCSp",
    level: 2,
    baseValue: 2.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCSp3",
    name: "Flying Camel Spin Level 3",
    kind: "spin",
    spinFamily: "FCSp",
    level: 3,
    baseValue: 2.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCSp4",
    name: "Flying Camel Spin Level 4",
    kind: "spin",
    spinFamily: "FCSp",
    level: 4,
    baseValue: 3.5,
    goeMin: -5,
    goeMax: 5,
  },
  // Flying Combination Spin (FCoSp)
  {
    code: "FCoSpB",
    name: "Flying Combination Spin Basic",
    kind: "spin",
    spinFamily: "FCoSp",
    level: "B",
    baseValue: 1.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCoSp1",
    name: "Flying Combination Spin Level 1",
    kind: "spin",
    spinFamily: "FCoSp",
    level: 1,
    baseValue: 1.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCoSp2",
    name: "Flying Combination Spin Level 2",
    kind: "spin",
    spinFamily: "FCoSp",
    level: 2,
    baseValue: 2.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCoSp3",
    name: "Flying Combination Spin Level 3",
    kind: "spin",
    spinFamily: "FCoSp",
    level: 3,
    baseValue: 3.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FCoSp4",
    name: "Flying Combination Spin Level 4",
    kind: "spin",
    spinFamily: "FCoSp",
    level: 4,
    baseValue: 3.5,
    goeMin: -5,
    goeMax: 5,
  },

  // ── STEP SEQUENCES ─────────────────────────────────────────────────────────
  {
    code: "StSqB",
    name: "Step Sequence Basic",
    kind: "stepSequence",
    level: "B",
    baseValue: 1.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "StSq1",
    name: "Step Sequence Level 1",
    kind: "stepSequence",
    level: 1,
    baseValue: 2.6,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "StSq2",
    name: "Step Sequence Level 2",
    kind: "stepSequence",
    level: 2,
    baseValue: 3.45,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "StSq3",
    name: "Step Sequence Level 3",
    kind: "stepSequence",
    level: 3,
    baseValue: 4.2,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "StSq4",
    name: "Step Sequence Level 4",
    kind: "stepSequence",
    level: 4,
    baseValue: 5.1,
    goeMin: -5,
    goeMax: 5,
  },
  // Choreographic step sequence — no level variants; always scored at "1" GOE tier.
  {
    code: "ChSq1",
    name: "Choreographic Step Sequence",
    kind: "chorSequence",
    baseValue: 3.0,
    goeMin: -5,
    goeMax: 5,
  },

  // ── DEATH SPIRALS (Pairs) ────────────────────────────────────────────────
  // Forward Inside entry (FoI → FiDs codes) — rarest and highest-value family
  {
    code: "FiDsB",
    name: "Forward Inside Death Spiral Basic",
    kind: "deathSpiral",
    entry: "FoI",
    level: "B",
    baseValue: 2.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FiDs1",
    name: "Forward Inside Death Spiral Level 1",
    kind: "deathSpiral",
    entry: "FoI",
    level: 1,
    baseValue: 3.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FiDs2",
    name: "Forward Inside Death Spiral Level 2",
    kind: "deathSpiral",
    entry: "FoI",
    level: 2,
    baseValue: 3.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FiDs3",
    name: "Forward Inside Death Spiral Level 3",
    kind: "deathSpiral",
    entry: "FoI",
    level: 3,
    baseValue: 4.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FiDs4",
    name: "Forward Inside Death Spiral Level 4",
    kind: "deathSpiral",
    entry: "FoI",
    level: 4,
    baseValue: 5.1,
    goeMin: -5,
    goeMax: 5,
  },
  // Forward Outside entry (FoO → FoDs codes)
  {
    code: "FoDsB",
    name: "Forward Outside Death Spiral Basic",
    kind: "deathSpiral",
    entry: "FoO",
    level: "B",
    baseValue: 2.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FoDs1",
    name: "Forward Outside Death Spiral Level 1",
    kind: "deathSpiral",
    entry: "FoO",
    level: 1,
    baseValue: 3.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FoDs2",
    name: "Forward Outside Death Spiral Level 2",
    kind: "deathSpiral",
    entry: "FoO",
    level: 2,
    baseValue: 3.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FoDs3",
    name: "Forward Outside Death Spiral Level 3",
    kind: "deathSpiral",
    entry: "FoO",
    level: 3,
    baseValue: 4.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "FoDs4",
    name: "Forward Outside Death Spiral Level 4",
    kind: "deathSpiral",
    entry: "FoO",
    level: 4,
    baseValue: 4.75,
    goeMin: -5,
    goeMax: 5,
  },
  // Backward Inside entry (BoI → BiDs codes)
  {
    code: "BiDsB",
    name: "Backward Inside Death Spiral Basic",
    kind: "deathSpiral",
    entry: "BoI",
    level: "B",
    baseValue: 2.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BiDs1",
    name: "Backward Inside Death Spiral Level 1",
    kind: "deathSpiral",
    entry: "BoI",
    level: 1,
    baseValue: 2.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BiDs2",
    name: "Backward Inside Death Spiral Level 2",
    kind: "deathSpiral",
    entry: "BoI",
    level: 2,
    baseValue: 3.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BiDs3",
    name: "Backward Inside Death Spiral Level 3",
    kind: "deathSpiral",
    entry: "BoI",
    level: 3,
    baseValue: 3.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BiDs4",
    name: "Backward Inside Death Spiral Level 4",
    kind: "deathSpiral",
    entry: "BoI",
    level: 4,
    baseValue: 4.55,
    goeMin: -5,
    goeMax: 5,
  },
  // Backward Outside entry (BoO → BoDs codes) — most common in competition
  {
    code: "BoDsB",
    name: "Backward Outside Death Spiral Basic",
    kind: "deathSpiral",
    entry: "BoO",
    level: "B",
    baseValue: 2.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BoDs1",
    name: "Backward Outside Death Spiral Level 1",
    kind: "deathSpiral",
    entry: "BoO",
    level: 1,
    baseValue: 2.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BoDs2",
    name: "Backward Outside Death Spiral Level 2",
    kind: "deathSpiral",
    entry: "BoO",
    level: 2,
    baseValue: 3.0,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BoDs3",
    name: "Backward Outside Death Spiral Level 3",
    kind: "deathSpiral",
    entry: "BoO",
    level: 3,
    baseValue: 3.5,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "BoDs4",
    name: "Backward Outside Death Spiral Level 4",
    kind: "deathSpiral",
    entry: "BoO",
    level: 4,
    baseValue: 4.25,
    goeMin: -5,
    goeMax: 5,
  },

  // ── LIFTS — Pairs, representative sample (Group 3 / 4 / 5R) ─────────────
  // Additional lift groups (1, 2), twist-lift grades, and ice-dance lifts
  // can be appended in Phase 4.3 once the full pairs element set is scoped.
  {
    code: "3Li1",
    name: "Group 3 Lift Level 1",
    kind: "lift",
    level: 1,
    baseValue: 4.4,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3Li2",
    name: "Group 3 Lift Level 2",
    kind: "lift",
    level: 2,
    baseValue: 5.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3Li3",
    name: "Group 3 Lift Level 3",
    kind: "lift",
    level: 3,
    baseValue: 6.2,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "3Li4",
    name: "Group 3 Lift Level 4",
    kind: "lift",
    level: 4,
    baseValue: 7.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4Li1",
    name: "Group 4 Lift Level 1",
    kind: "lift",
    level: 1,
    baseValue: 4.8,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4Li2",
    name: "Group 4 Lift Level 2",
    kind: "lift",
    level: 2,
    baseValue: 5.6,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4Li3",
    name: "Group 4 Lift Level 3",
    kind: "lift",
    level: 3,
    baseValue: 6.6,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "4Li4",
    name: "Group 4 Lift Level 4",
    kind: "lift",
    level: 4,
    baseValue: 7.7,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "5RLi1",
    name: "Group 5 Reverse Lift Level 1",
    kind: "lift",
    level: 1,
    baseValue: 4.4,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "5RLi2",
    name: "Group 5 Reverse Lift Level 2",
    kind: "lift",
    level: 2,
    baseValue: 5.3,
    goeMin: -5,
    goeMax: 5,
  },

  // ── THROW JUMPS — Pairs, triple family ───────────────────────────────────
  // Additional rotations (single, double, quad) can be appended in Phase 4.3.
  {
    code: "Th3T",
    name: "Throw Triple Toe Loop",
    kind: "throw",
    jumpType: "T",
    turns: 3,
    baseValue: 4.2,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "Th3S",
    name: "Throw Triple Salchow",
    kind: "throw",
    jumpType: "S",
    turns: 3,
    baseValue: 4.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "Th3Lo",
    name: "Throw Triple Loop",
    kind: "throw",
    jumpType: "Lo",
    turns: 3,
    baseValue: 4.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "Th3F",
    name: "Throw Triple Flip",
    kind: "throw",
    jumpType: "F",
    turns: 3,
    baseValue: 5.3,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "Th3Lz",
    name: "Throw Triple Lutz",
    kind: "throw",
    jumpType: "Lz",
    turns: 3,
    baseValue: 5.9,
    goeMin: -5,
    goeMax: 5,
  },
  {
    code: "Th3A",
    name: "Throw Triple Axel",
    kind: "throw",
    jumpType: "A",
    turns: 3,
    baseValue: 8.0,
    goeMin: -5,
    goeMax: 5,
  },
];
