
export type Athlete = {
  id: string
  name: string
  level: string
  group: string
  status: string
  avatar: string
  email: string
  parent: string
}

export const athletes: Athlete[] = [
  {
    id: "ATH-001",
    name: "Sophia Miller",
    level: "Level 8",
    group: "Elite Squad",
    status: "Active",
    avatar: "/avatars/01.png",
    email: "sophia.m@example.com",
    parent: "Sarah Miller",
  },
  {
    id: "ATH-002",
    name: "Olivia Chen",
    level: "Elite",
    group: "National Team",
    status: "Injured",
    avatar: "/avatars/02.png",
    email: "olivia.c@example.com",
    parent: "David Chen",
  },
  {
    id: "ATH-003",
    name: "Isabella Jones",
    level: "Level 4",
    group: "Juniors A",
    status: "Active",
    avatar: "/avatars/03.png",
    email: "isa.jones@example.com",
    parent: "Jessica Jones",
  },
  {
    id: "ATH-004",
    name: "Mia Wilson",
    level: "Level 6",
    group: "Elite Squad",
    status: "Active",
    avatar: "/avatars/04.png",
    email: "mia.w@example.com",
    parent: "Tom Wilson",
  },
  {
    id: "ATH-005",
    name: "Charlotte Brown",
    level: "Level 3",
    group: "Development",
    status: "On Leave",
    avatar: "/avatars/05.png",
    email: "charlotte.b@example.com",
    parent: "Amanda Brown",
  },
  {
    id: "ATH-006",
    name: "Ava Davis",
    level: "Level 9",
    group: "Elite Squad",
    status: "Active",
    avatar: "/avatars/06.png",
    email: "ava.d@example.com",
    parent: "Robert Davis",
  },
  {
    id: "ATH-007",
    name: "Emma Taylor",
    level: "Level 5",
    group: "Juniors B",
    status: "Active",
    avatar: "/avatars/01.png",
    email: "emma.t@example.com",
    parent: "Jennifer Taylor",
  },
  {
    id: "ATH-008",
    name: "Lucas Anderson",
    level: "Level 7",
    group: "Boys Team",
    status: "Active",
    avatar: "/avatars/02.png",
    email: "lucas.a@example.com",
    parent: "Michael Anderson",
  },
  {
    id: "ATH-009",
    name: "Amelia Thomas",
    level: "Level 2",
    group: "Development",
    status: "Active",
    avatar: "/avatars/03.png",
    email: "amelia.t@example.com",
    parent: "Elizabeth Thomas",
  },
  {
    id: "ATH-010",
    name: "Mason Martinez",
    level: "Level 6",
    group: "Boys Team",
    status: "Injured",
    avatar: "/avatars/04.png",
    email: "mason.m@example.com",
    parent: "Daniel Martinez",
  },
  {
    id: "ATH-011",
    name: "Harper White",
    level: "Level 4",
    group: "Juniors A",
    status: "Active",
    avatar: "/avatars/05.png",
    email: "harper.w@example.com",
    parent: "William White",
  },
  {
    id: "ATH-012",
    name: "Evelyn Harris",
    level: "Level 8",
    group: "Elite Squad",
    status: "Active",
    avatar: "/avatars/06.png",
    email: "evelyn.h@example.com",
    parent: "Joseph Harris",
  },
  {
    id: "ATH-013",
    name: "Abigail Martin",
    level: "Level 3",
    group: "Development",
    status: "Active",
    avatar: "/avatars/01.png",
    email: "abigail.m@example.com",
    parent: "Charles Martin",
  },
  {
    id: "ATH-014",
    name: "Ella Thompson",
    level: "Elite",
    group: "National Team",
    status: "Active",
    avatar: "/avatars/02.png",
    email: "ella.t@example.com",
    parent: "Christopher Thompson",
  },
  {
    id: "ATH-015",
    name: "Scarlett Garcia",
    level: "Level 5",
    group: "Juniors B",
    status: "On Leave",
    avatar: "/avatars/03.png",
    email: "scarlett.g@example.com",
    parent: "Patricia Garcia",
  },
  {
    id: "ATH-016",
    name: "Henry Robinson",
    level: "Level 7",
    group: "Boys Team",
    status: "Active",
    avatar: "/avatars/04.png",
    email: "henry.r@example.com",
    parent: "Thomas Robinson",
  },
  {
    id: "ATH-017",
    name: "Aria Clark",
    level: "Level 9",
    group: "Elite Squad",
    status: "Active",
    avatar: "/avatars/05.png",
    email: "aria.c@example.com",
    parent: "Mark Clark",
  },
  {
    id: "ATH-018",
    name: "Chloe Lewis",
    level: "Level 2",
    group: "Development",
    status: "Active",
    avatar: "/avatars/06.png",
    email: "chloe.l@example.com",
    parent: "Donald Lewis",
  },
  {
    id: "ATH-019",
    name: "Jackson Walker",
    level: "Level 5",
    group: "Boys Team",
    status: "Active",
    avatar: "/avatars/01.png",
    email: "jackson.w@example.com",
    parent: "Paul Walker",
  },
  {
    id: "ATH-020",
    name: "Grace Hall",
    level: "Level 4",
    group: "Juniors A",
    status: "Injured",
    avatar: "/avatars/02.png",
    email: "grace.h@example.com",
    parent: "Steven Hall",
  },
  {
    id: "ATH-021",
    name: "Lily Allen",
    level: "Level 6",
    group: "Elite Squad",
    status: "Active",
    avatar: "/avatars/03.png",
    email: "lily.a@example.com",
    parent: "Kenneth Allen",
  },
  {
    id: "ATH-022",
    name: "Sebastian Young",
    level: "Level 8",
    group: "Boys Team",
    status: "Active",
    avatar: "/avatars/04.png",
    email: "sebastian.y@example.com",
    parent: "George Young",
  },
  {
    id: "ATH-023",
    name: "Sofia King",
    level: "Level 3",
    group: "Development",
    status: "Active",
    avatar: "/avatars/05.png",
    email: "sofia.k@example.com",
    parent: "Edward King",
  },
  {
    id: "ATH-024",
    name: "Avery Wright",
    level: "Level 7",
    group: "Juniors B",
    status: "Active",
    avatar: "/avatars/06.png",
    email: "avery.w@example.com",
    parent: "Brian Wright",
  }
]

