"use client";

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import { api, ApiError } from "@/lib/api-client";

export interface Season {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  color: string;
  startDate: string;
  endDate: string;
  status: "DRAFT" | "ACTIVE" | "CLOSED" | "EXPIRED" | "CANCELLED";
  isRecurring: boolean;
  renewalLeadDays: number;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  _count?: {
    programs: number;
    memberships: number;
    competitions: number;
  };
}

export interface SeasonsListResponse {
  data: Season[];
  total: number;
  limit: number;
  offset: number;
}

export interface SeasonsQueryParams {
  status?: string;
  search?: string;
  limit?: number;
  offset?: number;
}

export interface CreateSeasonPayload {
  name: string;
  description?: string;
  color?: string;
  startDate: string;
  endDate: string;
  status?: "DRAFT" | "ACTIVE";
  isRecurring?: boolean;
  renewalLeadDays?: number;
}

export interface UpdateSeasonPayload {
  name?: string;
  description?: string | null;
  color?: string;
  startDate?: string;
  endDate?: string;
  status?: "DRAFT" | "ACTIVE" | "CLOSED" | "EXPIRED" | "CANCELLED";
  isRecurring?: boolean;
  renewalLeadDays?: number;
}

interface UseSeasonsOptions {
  autoFetch?: boolean;
  initialParams?: SeasonsQueryParams;
}

interface UseSeasonsReturn {
  seasons: Season[];
  total: number;
  isLoading: boolean;
  isCreating: boolean;
  isDeleting: boolean;
  isFeatureGated: boolean;
  error: string | null;
  fetchSeasons: (params?: SeasonsQueryParams) => Promise<void>;
  createSeason: (data: CreateSeasonPayload) => Promise<Season | null>;
  updateSeason: (id: string, data: UpdateSeasonPayload) => Promise<Season | null>;
  deleteSeason: (id: string) => Promise<boolean>;
  refresh: () => Promise<void>;
  clearError: () => void;
}

// Module-level stale-while-revalidate cache for the list query.
const LIST_CACHE_TTL_MS = 60_000;
type ListCacheEntry = {
  data: Season[];
  total: number;
  fetchedAt: number;
};
const listCache = new Map<string, ListCacheEntry>();

function paramsKey(params: SeasonsQueryParams): string {
  return JSON.stringify(params ?? {});
}

function invalidateLists() {
  listCache.clear();
}

export function useSeasons(options: UseSeasonsOptions = {}): UseSeasonsReturn {
  const { autoFetch = true, initialParams = {} } = options;
  const { data: session } = useSession();

  // Seed state from cache so revisits render instantly with no spinner.
  const initialKey = paramsKey(initialParams);
  const initialCached = listCache.get(initialKey);

  const [seasons, setSeasons] = useState<Season[]>(() => initialCached?.data ?? []);
  const [total, setTotal] = useState(() => initialCached?.total ?? 0);
  const [isLoading, setIsLoading] = useState(() => autoFetch && !initialCached);
  const [isCreating, setIsCreating] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isFeatureGated, setIsFeatureGated] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentParams, setCurrentParams] = useState<SeasonsQueryParams>(initialParams);

  const fetchSeasons = useCallback(
    async (params?: SeasonsQueryParams) => {
      const queryParams = params ?? currentParams;
      setCurrentParams(queryParams);

      const key = paramsKey(queryParams);
      const cached = listCache.get(key);
      if (!cached) setIsLoading(true);
      setError(null);

      try {
        const response = await api.get<SeasonsListResponse>("/api/seasons", queryParams);
        setSeasons(response.data);
        setTotal(response.total);
        listCache.set(key, {
          data: response.data,
          total: response.total,
          fetchedAt: Date.now(),
        });
      } catch (err) {
        const message = err instanceof ApiError ? err.message : "Failed to fetch seasons";
        setError(message);
        setIsFeatureGated(err instanceof ApiError && err.status === 403);
        console.error("Error fetching seasons:", err);
      } finally {
        setIsLoading(false);
      }
    },
    [currentParams]
  );

  const createSeason = useCallback(async (data: CreateSeasonPayload): Promise<Season | null> => {
    setIsCreating(true);
    setError(null);

    try {
      const newSeason = await api.post<Season>("/api/seasons", data);
      setSeasons((prev) => [newSeason, ...prev]);
      setTotal((prev) => prev + 1);
      invalidateLists();
      return newSeason;
    } catch (err) {
      const message = err instanceof ApiError ? err.message : "Failed to create season";
      setError(message);
      console.error("Error creating season:", err);
      return null;
    } finally {
      setIsCreating(false);
    }
  }, []);

  const updateSeason = useCallback(
    async (id: string, data: UpdateSeasonPayload): Promise<Season | null> => {
      setError(null);

      try {
        const updated = await api.patch<Season>(`/api/seasons/${id}`, data);
        setSeasons((prev) => prev.map((s) => (s.id === id ? updated : s)));
        invalidateLists();
        return updated;
      } catch (err) {
        const message = err instanceof ApiError ? err.message : "Failed to update season";
        setError(message);
        console.error("Error updating season:", err);
        return null;
      }
    },
    []
  );

  const deleteSeason = useCallback(async (id: string): Promise<boolean> => {
    setIsDeleting(true);
    setError(null);

    try {
      await api.delete(`/api/seasons/${id}`);
      setSeasons((prev) => prev.filter((s) => s.id !== id));
      setTotal((prev) => prev - 1);
      invalidateLists();
      return true;
    } catch (err) {
      const message = err instanceof ApiError ? err.message : "Failed to delete season";
      setError(message);
      console.error("Error deleting season:", err);
      return false;
    } finally {
      setIsDeleting(false);
    }
  }, []);

  const refresh = useCallback(async () => {
    await fetchSeasons(currentParams);
  }, [fetchSeasons, currentParams]);

  const clearError = useCallback(() => {
    setError(null);
  }, []);

  useEffect(() => {
    if (!autoFetch || !session?.user?.organizationId) return;
    const key = paramsKey(initialParams);
    const cached = listCache.get(key);
    const isFresh = cached && Date.now() - cached.fetchedAt < LIST_CACHE_TTL_MS;
    if (isFresh) return;
    fetchSeasons(initialParams);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session?.user?.organizationId]);

  return {
    seasons,
    total,
    isLoading,
    isCreating,
    isDeleting,
    isFeatureGated,
    error,
    fetchSeasons,
    createSeason,
    updateSeason,
    deleteSeason,
    refresh,
    clearError,
  };
}
