-- CreateEnum
CREATE TYPE "MembershipInstanceStatus" AS ENUM ('DRAFT', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'ARCHIVED');

-- AlterEnum
ALTER TYPE "BillingInterval" ADD VALUE 'ONE_TIME';

-- AlterTable: MembershipGroup - add new fields
ALTER TABLE "MembershipGroup" ADD COLUMN "isRecurring" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "defaultPrice" DECIMAL(10,2);
ALTER TABLE "MembershipGroup" ADD COLUMN "defaultBillingInterval" "BillingInterval" NOT NULL DEFAULT 'ONE_TIME';
ALTER TABLE "MembershipGroup" ADD COLUMN "autoGenerateInstances" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "generationLeadDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "MembershipGroup" ADD COLUMN "purchaseWindowDays" INTEGER;
ALTER TABLE "MembershipGroup" ADD COLUMN "capacity" INTEGER;
ALTER TABLE "MembershipGroup" ADD COLUMN "hasGenderRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "hasAgeRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "hasLevelRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "hasCapacityRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "hasWaiverRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "hasMedicalRequirement" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MembershipGroup" ADD COLUMN "allowedGenders" "GenderDeclaration"[];
ALTER TABLE "MembershipGroup" ADD COLUMN "minAge" INTEGER;
ALTER TABLE "MembershipGroup" ADD COLUMN "maxAge" INTEGER;

-- AlterTable: MembershipInstance - add new fields and change status type
ALTER TABLE "MembershipInstance" ADD COLUMN "purchaseStartDate" TIMESTAMP(3);
ALTER TABLE "MembershipInstance" ADD COLUMN "purchaseEndDate" TIMESTAMP(3);
ALTER TABLE "MembershipInstance" ADD COLUMN "capacity" INTEGER;
ALTER TABLE "MembershipInstance" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- Migrate MembershipInstance status from MembershipStatus to MembershipInstanceStatus
-- Step 1: Add new column with new enum type
ALTER TABLE "MembershipInstance" ADD COLUMN "status_new" "MembershipInstanceStatus" NOT NULL DEFAULT 'DRAFT';

-- Step 2: Copy existing status values (same names exist in both enums)
UPDATE "MembershipInstance" SET "status_new" = CASE
  WHEN "status"::text = 'ACTIVE' THEN 'ACTIVE'::"MembershipInstanceStatus"
  WHEN "status"::text = 'EXPIRED' THEN 'EXPIRED'::"MembershipInstanceStatus"
  WHEN "status"::text = 'CANCELLED' THEN 'CANCELLED'::"MembershipInstanceStatus"
  WHEN "status"::text = 'ARCHIVED' THEN 'ARCHIVED'::"MembershipInstanceStatus"
  ELSE 'DRAFT'::"MembershipInstanceStatus"
END;

-- Step 3: Drop old column and rename new one
ALTER TABLE "MembershipInstance" DROP COLUMN "status";
ALTER TABLE "MembershipInstance" RENAME COLUMN "status_new" TO "status";

-- AlterTable: Program - add gender restriction fields
ALTER TABLE "Program" ADD COLUMN "hasGenderRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Program" ADD COLUMN "allowedGenders" "GenderDeclaration"[];

-- AlterTable: LineItem - add membershipInstanceId
ALTER TABLE "LineItem" ADD COLUMN "membershipInstanceId" TEXT;

-- CreateTable: MembershipGroupLevelRequirement
CREATE TABLE "MembershipGroupLevelRequirement" (
    "id" TEXT NOT NULL,
    "membershipGroupId" TEXT NOT NULL,
    "levelId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MembershipGroupLevelRequirement_pkey" PRIMARY KEY ("id")
);

-- CreateTable: MembershipGroupWaiverRequirement
CREATE TABLE "MembershipGroupWaiverRequirement" (
    "id" TEXT NOT NULL,
    "membershipGroupId" TEXT NOT NULL,
    "waiverId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MembershipGroupWaiverRequirement_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "MembershipGroupLevelRequirement_membershipGroupId_idx" ON "MembershipGroupLevelRequirement"("membershipGroupId");
CREATE INDEX "MembershipGroupLevelRequirement_levelId_idx" ON "MembershipGroupLevelRequirement"("levelId");
CREATE UNIQUE INDEX "MembershipGroupLevelRequirement_membershipGroupId_levelId_key" ON "MembershipGroupLevelRequirement"("membershipGroupId", "levelId");

CREATE INDEX "MembershipGroupWaiverRequirement_membershipGroupId_idx" ON "MembershipGroupWaiverRequirement"("membershipGroupId");
CREATE INDEX "MembershipGroupWaiverRequirement_waiverId_idx" ON "MembershipGroupWaiverRequirement"("waiverId");
CREATE UNIQUE INDEX "MembershipGroupWaiverRequirement_membershipGroupId_waiverId_key" ON "MembershipGroupWaiverRequirement"("membershipGroupId", "waiverId");

-- AddForeignKey
ALTER TABLE "MembershipGroupLevelRequirement" ADD CONSTRAINT "MembershipGroupLevelRequirement_membershipGroupId_fkey" FOREIGN KEY ("membershipGroupId") REFERENCES "MembershipGroup"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MembershipGroupLevelRequirement" ADD CONSTRAINT "MembershipGroupLevelRequirement_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "Level"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MembershipGroupWaiverRequirement" ADD CONSTRAINT "MembershipGroupWaiverRequirement_membershipGroupId_fkey" FOREIGN KEY ("membershipGroupId") REFERENCES "MembershipGroup"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MembershipGroupWaiverRequirement" ADD CONSTRAINT "MembershipGroupWaiverRequirement_waiverId_fkey" FOREIGN KEY ("waiverId") REFERENCES "Waiver"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_membershipInstanceId_fkey" FOREIGN KEY ("membershipInstanceId") REFERENCES "MembershipInstance"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Data Migration: Set existing MembershipGroups as non-recurring with defaults from their first instance
UPDATE "MembershipGroup" mg
SET
  "isRecurring" = CASE WHEN mg."allowAutoRenew" = true THEN true ELSE false END,
  "defaultPrice" = sub."price",
  "defaultBillingInterval" = sub."billingInterval"
FROM (
  SELECT DISTINCT ON (mi."membershipGroupId")
    mi."membershipGroupId",
    mi."price",
    mi."billingInterval"
  FROM "MembershipInstance" mi
  ORDER BY mi."membershipGroupId", mi."createdAt" ASC
) sub
WHERE mg."id" = sub."membershipGroupId";

-- For non-recurring groups, mark their first instance as auto-generated
UPDATE "MembershipInstance" mi
SET "isAutoGenerated" = true
FROM "MembershipGroup" mg
WHERE mi."membershipGroupId" = mg."id"
  AND mg."isRecurring" = false
  AND mi."id" = (
    SELECT mi2."id"
    FROM "MembershipInstance" mi2
    WHERE mi2."membershipGroupId" = mg."id"
    ORDER BY mi2."createdAt" ASC
    LIMIT 1
  );
