export type BillingInterval = "ONE_TIME" | "MONTHLY" | "YEARLY" | "SESSION";
export type MembershipStatus = "ACTIVE" | "EXPIRED" | "CANCELLED" | "ARCHIVED";
export type MembershipInstanceStatus = "DRAFT" | "ACTIVE" | "EXPIRED" | "CANCELLED" | "ARCHIVED";
export type GenderDeclaration = "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";

// Types
export interface MembershipGroup {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  programTypes: string[];

  // Recurrence Configuration
  isRecurring: boolean;
  allowAutoRenew: boolean;

  // Default Pricing
  defaultPrice: number | null;
  defaultBillingInterval: BillingInterval;

  // Instance Generation
  autoGenerateInstances: boolean;
  generationLeadDays: number;

  // Purchase Window
  purchaseWindowDays: number | null;

  // Capacity
  capacity: number | null;

  // Restriction Flags
  hasGenderRestriction: boolean;
  hasAgeRestriction: boolean;
  hasLevelRestriction: boolean;
  hasCapacityRestriction: boolean;
  hasWaiverRestriction: boolean;
  hasMedicalRequirement: boolean;

  // Restriction Values
  allowedGenders: GenderDeclaration[];
  minAge: number | null;
  maxAge: number | null;

  createdAt: string;
  updatedAt: string;
  instances?: MembershipInstance[];
  levelRequirements?: MembershipGroupLevelRequirement[];
  waiverRequirements?: MembershipGroupWaiverRequirement[];
  _count?: {
    instances: number;
  };
}

export interface MembershipInstance {
  id: string;
  membershipGroupId: string;
  name: string;
  price: number;
  billingInterval: BillingInterval;
  startDate: string;
  endDate: string;

  // Purchase Window Overrides
  purchaseStartDate: string | null;
  purchaseEndDate: string | null;

  // Capacity override
  capacity: number | null;

  // Renewal
  autoRenewDate: string | null;

  // Auto-generation tracking
  isAutoGenerated: boolean;

  status: MembershipInstanceStatus;
  createdAt: string;
  updatedAt: string;
  group?: MembershipGroup;
  _count?: {
    athleteMemberships: number;
  };
}

export interface AthleteMembership {
  id: string;
  athleteId: string;
  membershipInstanceId: string;
  startDate: string;
  endDate: string | null;
  status: MembershipStatus;
  autoRenew: boolean;
  createdAt: string;
  updatedAt: string;
  athlete?: {
    id: string;
    firstName: string;
    lastName: string;
    name: string;
    customId: string | null;
  };
  instance?: MembershipInstance;
}

export interface MembershipGroupLevelRequirement {
  id: string;
  membershipGroupId: string;
  levelId: string;
  createdAt: string;
  level?: {
    id: string;
    name: string;
    color: string | null;
  };
}

export interface MembershipGroupWaiverRequirement {
  id: string;
  membershipGroupId: string;
  waiverId: string;
  createdAt: string;
  waiver?: {
    id: string;
    title: string;
    status: string;
  };
}

export interface MembershipGroupsListResponse {
  data: MembershipGroup[];
  total: number;
  limit: number;
  offset: number;
}

export interface CreateMembershipGroupPayload {
  name: string;
  description?: string;
  programTypes?: string[];
  isRecurring?: boolean;
  allowAutoRenew?: boolean;
  defaultPrice?: number;
  defaultBillingInterval?: BillingInterval;
  autoGenerateInstances?: boolean;
  generationLeadDays?: number;
  purchaseWindowDays?: number | null;
  capacity?: number | null;

  // Restriction flags
  hasGenderRestriction?: boolean;
  hasAgeRestriction?: boolean;
  hasLevelRestriction?: boolean;
  hasCapacityRestriction?: boolean;
  hasWaiverRestriction?: boolean;
  hasMedicalRequirement?: boolean;

  // Restriction values
  allowedGenders?: GenderDeclaration[];
  minAge?: number | null;
  maxAge?: number | null;
}

export interface UpdateMembershipGroupPayload extends Partial<CreateMembershipGroupPayload> {}

export interface CreateMembershipInstancePayload {
  membershipGroupId: string;
  name: string;
  price: number;
  billingInterval: BillingInterval;
  startDate: string;
  endDate: string;
  autoRenewDate?: string;
  purchaseStartDate?: string;
  purchaseEndDate?: string;
  capacity?: number;
  status?: MembershipInstanceStatus;
}

export interface MembershipsQueryParams {
  limit?: number;
  offset?: number;
  include?: string;
}
