-- CreateEnum
CREATE TYPE "SeasonStatus" AS ENUM ('DRAFT', 'ACTIVE', 'EXPIRED', 'CANCELLED');

-- CreateTable
CREATE TABLE "Season" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "color" TEXT NOT NULL DEFAULT '#8b5cf6',
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "status" "SeasonStatus" NOT NULL DEFAULT 'DRAFT',
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "autoRenewDate" TIMESTAMP(3),
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Season_pkey" PRIMARY KEY ("id")
);

-- AlterTable: Add seasonId to Program
ALTER TABLE "Program" ADD COLUMN "seasonId" TEXT;

-- AlterTable: Add seasonId to MembershipGroup
ALTER TABLE "MembershipGroup" ADD COLUMN "seasonId" TEXT;

-- AlterTable: Add seasonId to Competition
ALTER TABLE "Competition" ADD COLUMN "seasonId" TEXT;

-- CreateIndex
CREATE INDEX "Season_organizationId_idx" ON "Season"("organizationId");
CREATE INDEX "Season_organizationId_status_idx" ON "Season"("organizationId", "status");
CREATE INDEX "Program_seasonId_idx" ON "Program"("seasonId");
CREATE INDEX "MembershipGroup_seasonId_idx" ON "MembershipGroup"("seasonId");
CREATE INDEX "Competition_seasonId_idx" ON "Competition"("seasonId");

-- AddForeignKey
ALTER TABLE "Program" ADD CONSTRAINT "Program_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "Season"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MembershipGroup" ADD CONSTRAINT "MembershipGroup_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "Season"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Competition" ADD CONSTRAINT "Competition_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "Season"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Season" ADD CONSTRAINT "Season_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
