import { db } from "@/lib/db";
import { addYears, addMonths, subDays } from "date-fns";

/**
 * Generates upcoming membership instances for recurring groups with auto-generation enabled.
 * Creates DRAFT instances that admins review and publish.
 * Should be run daily via cron.
 */
export async function generateUpcomingInstances() {
  const now = new Date();

  const recurringGroups = await db.membershipGroup.findMany({
    where: {
      isRecurring: true,
      autoGenerateInstances: true,
    },
    include: {
      instances: {
        orderBy: { endDate: "desc" },
        take: 1,
      },
    },
  });

  const results: Array<{ groupId: string; groupName: string; instanceName: string }> = [];

  for (const group of recurringGroups) {
    const latestInstance = group.instances[0];
    if (!latestInstance) continue;

    // Check if we should generate the next instance:
    // Generate when now is within generationLeadDays of the latest instance's end
    const generationThreshold = subDays(latestInstance.endDate, group.generationLeadDays);
    if (now < generationThreshold) continue;

    // Check if a future instance already exists (draft or active)
    const futureInstance = await db.membershipInstance.findFirst({
      where: {
        membershipGroupId: group.id,
        startDate: { gt: latestInstance.startDate },
      },
    });

    if (futureInstance) continue;

    // Calculate next period dates based on billing interval
    let nextStartDate = new Date(latestInstance.endDate);
    let nextEndDate: Date;
    let nextAutoRenewDate: Date | null = null;

    if (group.defaultBillingInterval === "YEARLY" || latestInstance.billingInterval === "YEARLY") {
      nextEndDate = addYears(nextStartDate, 1);
      if (latestInstance.autoRenewDate) {
        nextAutoRenewDate = addYears(new Date(latestInstance.autoRenewDate), 1);
      }
    } else if (group.defaultBillingInterval === "MONTHLY" || latestInstance.billingInterval === "MONTHLY") {
      nextEndDate = addMonths(nextStartDate, 1);
      if (latestInstance.autoRenewDate) {
        nextAutoRenewDate = addMonths(new Date(latestInstance.autoRenewDate), 1);
      }
    } else {
      // SESSION or ONE_TIME - skip auto-generation (can't predict period)
      continue;
    }

    // Auto-increment name (e.g., "FY25" -> "FY26", "Winter 2025" -> "Winter 2026")
    const nextName = latestInstance.name.replace(/\d+/, (match) => {
      const num = parseInt(match);
      return (num + 1).toString();
    });

    const newInstance = await db.membershipInstance.create({
      data: {
        membershipGroupId: group.id,
        name: nextName,
        price: group.defaultPrice ?? latestInstance.price,
        billingInterval: group.defaultBillingInterval !== "ONE_TIME"
          ? group.defaultBillingInterval
          : latestInstance.billingInterval,
        startDate: nextStartDate,
        endDate: nextEndDate,
        autoRenewDate: nextAutoRenewDate,
        status: "DRAFT",
        isAutoGenerated: true,
      },
    });

    results.push({
      groupId: group.id,
      groupName: group.name,
      instanceName: newInstance.name,
    });
  }

  return results;
}

/**
 * Checks for Membership Instances that need to be renewed (created for next term).
 * This handles the legacy auto-renew behavior where instances trigger renewal via autoRenewDate.
 * Should be run daily via cron.
 */
export async function processMembershipInstanceRenewals() {
  const now = new Date();

  const dueInstances = await db.membershipInstance.findMany({
    where: {
      autoRenewDate: {
        lte: now,
      },
      group: {
        allowAutoRenew: true,
      },
      status: { in: ["ACTIVE"] },
    },
    include: {
      group: true,
    },
  });

  const results: Array<{ previous: string; new: string; groupId: string }> = [];

  for (const instance of dueInstances) {
    const futureInstance = await db.membershipInstance.findFirst({
      where: {
        membershipGroupId: instance.membershipGroupId,
        startDate: {
          gt: instance.startDate,
        },
      },
    });

    if (futureInstance) continue;

    let nextStartDate = new Date(instance.startDate);
    let nextEndDate = new Date(instance.endDate);
    let nextAutoRenewDate = instance.autoRenewDate ? new Date(instance.autoRenewDate) : undefined;

    if (instance.billingInterval === "YEARLY") {
      nextStartDate = addYears(nextStartDate, 1);
      nextEndDate = addYears(nextEndDate, 1);
      if (nextAutoRenewDate) nextAutoRenewDate = addYears(nextAutoRenewDate, 1);
    } else if (instance.billingInterval === "MONTHLY") {
      nextStartDate = addMonths(nextStartDate, 1);
      nextEndDate = addMonths(nextEndDate, 1);
      if (nextAutoRenewDate) nextAutoRenewDate = addMonths(nextAutoRenewDate, 1);
    } else {
      continue;
    }

    const nextName = instance.name.replace(/\d+/, (match) => {
      const num = parseInt(match);
      return (num + 1).toString();
    });

    const newInstance = await db.membershipInstance.create({
      data: {
        membershipGroupId: instance.membershipGroupId,
        name: nextName,
        price: instance.price,
        billingInterval: instance.billingInterval,
        startDate: nextStartDate,
        endDate: nextEndDate,
        autoRenewDate: nextAutoRenewDate,
        status: "ACTIVE",
        isAutoGenerated: true,
      },
    });

    results.push({
      previous: instance.name,
      new: newInstance.name,
      groupId: instance.membershipGroupId,
    });
  }

  return results;
}

/**
 * Checks for Athlete Memberships that need to be renewed into the next instance.
 * Should be run daily via cron.
 */
export async function processAthleteRenewals() {
  const now = new Date();

  const expiringMemberships = await db.athleteMembership.findMany({
    where: {
      endDate: {
        lte: now,
      },
      status: "ACTIVE",
      autoRenew: true,
    },
    include: {
      instance: {
        include: {
          group: true,
        },
      },
      athlete: true,
    },
  });

  const renewals: Array<{ athlete: string; from: string; to: string }> = [];

  for (const membership of expiringMemberships) {
    const nextInstance = await db.membershipInstance.findFirst({
      where: {
        membershipGroupId: membership.instance.membershipGroupId,
        startDate: {
          gte: membership.instance.endDate,
        },
        status: "ACTIVE",
      },
      orderBy: {
        startDate: "asc",
      },
    });

    if (!nextInstance) continue;

    const existingNext = await db.athleteMembership.findFirst({
      where: {
        athleteId: membership.athleteId,
        membershipInstanceId: nextInstance.id,
      },
    });

    if (existingNext) continue;

    await db.athleteMembership.create({
      data: {
        athleteId: membership.athleteId,
        membershipInstanceId: nextInstance.id,
        startDate: nextInstance.startDate,
        endDate: nextInstance.endDate,
        status: "ACTIVE",
        autoRenew: true,
      },
    });

    const athleteName = `${membership.athlete.firstName || ""} ${membership.athlete.lastName || ""}`.trim() || membership.athlete.name;
    renewals.push({
      athlete: athleteName,
      from: membership.instance.name,
      to: nextInstance.name,
    });
  }

  return renewals;
}

/**
 * Expires membership instances past their end date.
 * Should be run daily via cron.
 */
export async function expireInstances() {
  const now = new Date();

  const result = await db.membershipInstance.updateMany({
    where: {
      endDate: { lt: now },
      status: "ACTIVE",
    },
    data: {
      status: "EXPIRED",
    },
  });

  return { expiredCount: result.count };
}
