import { db } from "@/lib/db";
import { addYears, addMonths, subDays } from "date-fns";

/**
 * Generates upcoming seasons for recurring seasons.
 * Uses each season's renewalLeadDays to decide when to generate.
 * Creates DRAFT seasons that admins review and publish.
 * Should be run daily via cron.
 */
export async function generateUpcomingSeasons() {
  const now = new Date();

  const recurringSeasons = await db.season.findMany({
    where: {
      isRecurring: true,
      status: "ACTIVE",
      organization: { isActive: true },
    },
    orderBy: { endDate: "desc" },
  });

  const results: Array<{ seasonId: string; seasonName: string; newName: string }> = [];

  const seen = new Set<string>();

  for (const season of recurringSeasons) {
    if (seen.has(season.organizationId + ":" + season.name)) continue;
    seen.add(season.organizationId + ":" + season.name);

    const generationThreshold = subDays(season.endDate, season.renewalLeadDays);
    if (now < generationThreshold) continue;

    const futureExists = await db.season.findFirst({
      where: {
        organizationId: season.organizationId,
        startDate: { gt: season.startDate },
        isAutoGenerated: true,
      },
    });

    if (futureExists) continue;

    const durationMs = season.endDate.getTime() - season.startDate.getTime();
    const durationDays = Math.round(durationMs / (1000 * 60 * 60 * 24));

    let nextStartDate = new Date(season.endDate);
    let nextEndDate: Date;

    if (durationDays >= 300) {
      nextEndDate = addYears(nextStartDate, 1);
    } else if (durationDays >= 25) {
      nextEndDate = addMonths(nextStartDate, Math.round(durationDays / 30));
    } else {
      nextEndDate = new Date(nextStartDate.getTime() + durationMs);
    }

    const nextName = season.name.replace(/\d+/, (match) => {
      const num = parseInt(match);
      return (num + 1).toString();
    });

    await db.season.create({
      data: {
        organizationId: season.organizationId,
        name: nextName,
        description: season.description,
        color: season.color,
        startDate: nextStartDate,
        endDate: nextEndDate,
        status: "DRAFT",
        isRecurring: true,
        renewalLeadDays: season.renewalLeadDays,
        isAutoGenerated: true,
      },
    });

    results.push({
      seasonId: season.id,
      seasonName: season.name,
      newName: nextName,
    });
  }

  return results;
}

/**
 * Expires seasons past their end date.
 * Should be run daily via cron.
 */
export async function expireSeasons() {
  const now = new Date();

  const result = await db.season.updateMany({
    where: {
      endDate: { lt: now },
      status: "ACTIVE",
    },
    data: {
      status: "EXPIRED",
    },
  });

  return { expiredCount: result.count };
}
