# Staging Environment Outputs

# =============================================================================
# S3 Buckets
# =============================================================================

output "assets_bucket_name" {
  description = "Name of the assets bucket"
  value       = module.s3.assets_bucket_name
}

output "assets_bucket_arn" {
  description = "ARN of the assets bucket"
  value       = module.s3.assets_bucket_arn
}

output "assets_bucket_url" {
  description = "Public URL for the assets bucket"
  value       = "https://${module.s3.assets_bucket_name}.s3.${var.aws_region}.amazonaws.com"
}

output "documents_bucket_name" {
  description = "Name of the documents bucket"
  value       = module.s3.documents_bucket_name
}

output "documents_bucket_arn" {
  description = "ARN of the documents bucket"
  value       = module.s3.documents_bucket_arn
}

# =============================================================================
# AWS SES Email Configuration
# =============================================================================

output "ses_domain" {
  description = "The domain verified in SES for sending emails"
  value       = aws_ses_domain_identity.staging.domain
}

output "ses_verification_token" {
  description = "TXT record value for SES domain verification. Add as TXT record: _amazonses.<domain>"
  value       = aws_ses_domain_identity.staging.verification_token
}

output "ses_dkim_tokens" {
  description = "DKIM CNAME records for email authentication. Add 3 CNAME records: <token>._domainkey.<domain> -> <token>.dkim.amazonses.com"
  value       = aws_ses_domain_dkim.staging.dkim_tokens
}

output "ses_from_email" {
  description = "The verified from email address for SES"
  value       = aws_ses_email_identity.noreply.email
}

# =============================================================================
# IAM Credentials (sensitive)
# =============================================================================

output "staging_access_key_id" {
  description = "Access key ID for the staging services user (S3 + SES)"
  value       = aws_iam_access_key.staging_services.id
  sensitive   = false  # Access key IDs are not secret
}

output "staging_secret_access_key" {
  description = "Secret access key for the staging services user (S3 + SES)"
  value       = aws_iam_access_key.staging_services.secret
  sensitive   = true
}

# =============================================================================
# Environment Variables for EC2
# =============================================================================

output "env_file_content" {
  description = "Environment variables to add to the EC2 staging instance"
  value       = <<-EOT
    # AWS Credentials (generated by Terraform - used for S3 and SES)
    AWS_ACCESS_KEY_ID=${aws_iam_access_key.staging_services.id}
    AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.staging_services.secret}

    # S3 Storage Configuration
    USE_S3_STORAGE=true
    AWS_S3_REGION=${var.aws_region}

    # SES Email Configuration
    AWS_SES_REGION=${var.aws_region}
    AWS_SES_FROM_EMAIL=noreply@${aws_ses_domain_identity.staging.domain}
  EOT
  sensitive   = true
}

# =============================================================================
# DNS Records Required (for manual configuration)
# =============================================================================

output "dns_records_required" {
  description = "DNS records that must be added for SES domain verification"
  value       = <<-EOT
    
    ============================================================
    SES Domain Verification - Add these DNS records:
    ============================================================
    
    1. Domain Verification (TXT Record):
       Name:  _amazonses.${aws_ses_domain_identity.staging.domain}
       Type:  TXT
       Value: ${aws_ses_domain_identity.staging.verification_token}
    
    2. DKIM Records (3 CNAME Records):
    %{for token in aws_ses_domain_dkim.staging.dkim_tokens~}
       Name:  ${token}._domainkey.${aws_ses_domain_identity.staging.domain}
       Type:  CNAME
       Value: ${token}.dkim.amazonses.com
    %{endfor~}
    
    ============================================================
    After adding DNS records, verification typically takes 5-15 minutes.
    Check status in AWS SES Console > Verified identities
    ============================================================
    
  EOT
}
